AWSTemplateFormatVersion: 2010-09-09
Description: EC2 Security Group stack for isucon.

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: isucon-sg-ec2
      GroupDescription: security group for ec2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 1323
          ToPort: 1323
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue isucon-VPC
      Tags:
        - Key: Name
          Value: isucon-sg

Outputs:
  SecurityGroup:
    Value: !Ref SecurityGroup
    Export:
      Name: isucon-sg
